### ISSUE TITLE
First event is lost 

### ISSUE THREAD

**Issue by CasianOlga** [zalando-incubator/paradox-nakadi-consumer#6]
First event is lost if ~earliest known~ oldest available offset is 0 because cursor in X-Nakadi-Consumer header is set to 0 (should be -1, i.e., 1 before the required offset).

>  Assumes the offset on each cursor is not inclusive (i.e., first delivered Event is the
            **first one after** the one pointed to in the cursor).

(see https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml)

Config used:

> partitionCoordinatorProvider: simple

**Comment by everesio** [comment]
SimplePartitionCoordinator uses either newest_available_offset or oldest_available_offset depending on
startNewestAvailableOffset configuration parameter.

http://localhost:8080/event-types/order.ORDER_RECEIVED/partitions provides following result after 

- 0 events 
  [{"oldest_available_offset":"0","newest_available_offset":"BEGIN","partition":"0"}]
- 1 event
  [{"oldest_available_offset":"0","newest_available_offset":"0","partition":"0"}]
- 2 events
  [{"oldest_available_offset":"0","newest_available_offset":"1","partition":"0"}]

were published.

In case of startNewestAvailableOffset is true, offset is set to consume next event which will be published (and not last one which has been published).
Using oldest_available_offset should give you possibility to replay events. 
In such a case decrementing the value would be really necessary.
